package com.example.ownvoice.ui.screens

import android.Manifest
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.pm.PackageManager
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.core.*
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import com.example.ownvoice.OwnVoiceApplication
import com.example.ownvoice.network.BridgeClient
import com.example.ownvoice.service.MeetingRecordingService
import com.example.ownvoice.theme.DesignTokens
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.text.SimpleDateFormat
import java.util.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MeetingModeScreen(
    onBack: () -> Unit
) {
    val context = LocalContext.current
    val app = context.applicationContext as OwnVoiceApplication
    val scope = rememberCoroutineScope()
    val bridgeClient = remember { BridgeClient(app.secureConfig, context) }

    val isRecording by MeetingRecordingService.isRecording.collectAsState()
    val durationSeconds by MeetingRecordingService.durationSeconds.collectAsState()
    val liveTranscript by MeetingRecordingService.liveTranscript.collectAsState()
    val decisions by MeetingRecordingService.decisions.collectAsState()
    val actionItems by MeetingRecordingService.actionItems.collectAsState()
    val executiveSummary by MeetingRecordingService.executiveSummary.collectAsState()
    val isProcessingChunk by MeetingRecordingService.isProcessingChunk.collectAsState()

    var meetingTitle by remember {
        mutableStateOf("Meeting - ${SimpleDateFormat("MMM d, HH:mm", Locale.getDefault()).format(Date())}")
    }
    var isSendingToPc by remember { mutableStateOf(false) }
    var showClearDialog by remember { mutableStateOf(false) }
    var isTranscriptExpanded by remember { mutableStateOf(false) }

    var hasMicPermission by remember {
        mutableStateOf(
            ContextCompat.checkSelfPermission(context, Manifest.permission.RECORD_AUDIO) == PackageManager.PERMISSION_GRANTED
        )
    }

    val micLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { granted ->
        hasMicPermission = granted
        if (granted) {
            MeetingRecordingService.start(context)
        } else {
            Toast.makeText(context, "Microphone permission is required for Meeting Mode", Toast.LENGTH_SHORT).show()
        }
    }

    fun formatDuration(seconds: Long): String {
        val hrs = seconds / 3600
        val mins = (seconds % 3600) / 60
        val secs = seconds % 60
        return if (hrs > 0) {
            String.format(Locale.getDefault(), "%02d:%02d:%02d", hrs, mins, secs)
        } else {
            String.format(Locale.getDefault(), "%02d:%02d", mins, secs)
        }
    }

    fun buildMarkdownDocument(): String {
        val sb = StringBuilder()
        sb.append("# $meetingTitle\n\n")
        sb.append("*Generated by OwnVoice Autonomous Meeting Studio*\n")
        sb.append("*Date: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())} | Duration: ${formatDuration(durationSeconds)}*\n\n")

        if (executiveSummary.isNotBlank()) {
            sb.append("## 📝 Executive Summary\n")
            sb.append(executiveSummary.trim())
            sb.append("\n\n")
        }

        if (decisions.isNotEmpty()) {
            sb.append("## 📌 Key Decisions\n")
            decisions.forEach { decision ->
                sb.append("- ").append(decision.trim()).append("\n")
            }
            sb.append("\n")
        }

        if (actionItems.isNotEmpty()) {
            sb.append("## ✅ Action Items\n")
            actionItems.forEach { item ->
                sb.append("- [ ] ").append(item.trim()).append("\n")
            }
            sb.append("\n")
        }

        if (liveTranscript.isNotBlank()) {
            sb.append("## 💬 Complete Transcript\n")
            sb.append(liveTranscript.trim())
            sb.append("\n")
        }

        return sb.toString()
    }

    fun copyMarkdownToClipboard() {
        val doc = buildMarkdownDocument()
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("Meeting Notes", doc)
        clipboard.setPrimaryClip(clip)
        Toast.makeText(context, "Meeting notes copied as Markdown", Toast.LENGTH_SHORT).show()
    }

    fun sendNotesToPc() {
        val doc = buildMarkdownDocument()
        if (doc.isBlank()) {
            Toast.makeText(context, "No meeting notes to send", Toast.LENGTH_SHORT).show()
            return
        }
        scope.launch {
            isSendingToPc = true
            val success = withContext(Dispatchers.IO) {
                bridgeClient.sendMeetingNotesToPc(meetingTitle, doc)
            }
            isSendingToPc = false
            if (success) {
                Toast.makeText(context, "Saved to PC Documents/OwnVoice_Notes!", Toast.LENGTH_LONG).show()
            } else {
                Toast.makeText(context, "Could not reach PC. Notes copied to phone clipboard instead.", Toast.LENGTH_SHORT).show()
                copyMarkdownToClipboard()
            }
        }
    }

    // Pulse animation for recording state
    val infiniteTransition = rememberInfiniteTransition(label = "pulse")
    val pulseScale by infiniteTransition.animateFloat(
        initialValue = 1.0f,
        targetValue = 1.15f,
        animationSpec = infiniteRepeatable(
            animation = tween(900, easing = FastOutSlowInEasing),
            repeatMode = RepeatMode.Reverse
        ),
        label = "pulseScale"
    )

    Scaffold(
        containerColor = DesignTokens.Colors.BackgroundDark,
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text(
                            text = "Meeting Studio",
                            fontSize = 18.sp,
                            fontWeight = FontWeight.Bold,
                            color = DesignTokens.Colors.TextPrimary
                        )
                        Text(
                            text = if (isRecording) "Recording • ${formatDuration(durationSeconds)}" else "Autonomous Minutes & AI Synthesis",
                            fontSize = 12.sp,
                            color = if (isRecording) DesignTokens.Colors.StatusRecording else DesignTokens.Colors.TextSubtle
                        )
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back",
                            tint = DesignTokens.Colors.TextPrimary
                        )
                    }
                },
                actions = {
                    IconButton(onClick = { showClearDialog = true }) {
                        Icon(
                            imageVector = Icons.Default.DeleteSweep,
                            contentDescription = "Clear Session",
                            tint = DesignTokens.Colors.TextMuted
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = DesignTokens.Colors.BackgroundDark
                )
            )
        }
    ) { paddingValues ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(horizontal = 18.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Meeting Title Field
            item {
                Spacer(modifier = Modifier.height(4.dp))
                Surface(
                    shape = RoundedCornerShape(12.dp),
                    color = DesignTokens.Colors.CardSurface,
                    border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.Colors.BorderSubtle),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(horizontal = 14.dp, vertical = 10.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Default.EditCalendar,
                            contentDescription = null,
                            tint = DesignTokens.Colors.PrimaryLightBlue,
                            modifier = Modifier.size(20.dp)
                        )
                        Spacer(modifier = Modifier.width(10.dp))
                        BasicTextField(
                            value = meetingTitle,
                            onValueChange = { meetingTitle = it },
                            textStyle = androidx.compose.ui.text.TextStyle(
                                color = DesignTokens.Colors.TextPrimary,
                                fontSize = 15.sp,
                                fontWeight = FontWeight.SemiBold
                            ),
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                }
            }

            // Big Recording Control & Waveform Hero Card
            item {
                Surface(
                    shape = RoundedCornerShape(18.dp),
                    color = DesignTokens.CardBgElevated,
                    border = androidx.compose.foundation.BorderStroke(
                        1.dp,
                        if (isRecording) DesignTokens.Colors.StatusRecording.copy(alpha = 0.5f)
                        else DesignTokens.Colors.BorderSubtle
                    ),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(
                        modifier = Modifier.padding(20.dp),
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        // Status & Processing Indicator
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.Center
                        ) {
                            if (isRecording) {
                                Box(
                                    modifier = Modifier
                                        .size(10.dp)
                                        .scale(pulseScale)
                                        .background(DesignTokens.Colors.StatusRecording, CircleShape)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "LIVE RECORDING",
                                    fontSize = 12.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = DesignTokens.Colors.StatusRecording,
                                    letterSpacing = 1.sp
                                )
                            } else {
                                Box(
                                    modifier = Modifier
                                        .size(8.dp)
                                        .background(DesignTokens.Colors.TextMuted, CircleShape)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "STANDBY",
                                    fontSize = 12.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = DesignTokens.Colors.TextMuted,
                                    letterSpacing = 1.sp
                                )
                            }

                            if (isProcessingChunk) {
                                Spacer(modifier = Modifier.width(12.dp))
                                CircularProgressIndicator(
                                    modifier = Modifier.size(14.dp),
                                    strokeWidth = 2.dp,
                                    color = DesignTokens.PurpleAccent
                                )
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(
                                    text = "Gemini Synthesizing...",
                                    fontSize = 11.sp,
                                    color = DesignTokens.PurpleAccent,
                                    fontWeight = FontWeight.Medium
                                )
                            }
                        }

                        Spacer(modifier = Modifier.height(14.dp))

                        // Large Timer Display
                        Text(
                            text = formatDuration(durationSeconds),
                            fontSize = 38.sp,
                            fontWeight = FontWeight.Bold,
                            color = DesignTokens.Colors.TextPrimary,
                            letterSpacing = 1.5.sp
                        )

                        Spacer(modifier = Modifier.height(16.dp))

                        // Animated Waveform Simulation when recording
                        if (isRecording) {
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(28.dp),
                                horizontalArrangement = Arrangement.SpaceEvenly,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                repeat(18) { index ->
                                    val barScale by infiniteTransition.animateFloat(
                                        initialValue = 0.2f + (index % 5) * 0.15f,
                                        targetValue = 0.95f - (index % 4) * 0.12f,
                                        animationSpec = infiniteRepeatable(
                                            animation = tween(400 + (index * 45), easing = FastOutSlowInEasing),
                                            repeatMode = RepeatMode.Reverse
                                        ),
                                        label = "waveBar$index"
                                    )
                                    Box(
                                        modifier = Modifier
                                            .width(4.dp)
                                            .fillMaxHeight(barScale)
                                            .clip(RoundedCornerShape(2.dp))
                                            .background(
                                                Brush.verticalGradient(
                                                    listOf(DesignTokens.Colors.PrimaryLightBlue, DesignTokens.PurpleAccent)
                                                )
                                            )
                                    )
                                }
                            }
                            Spacer(modifier = Modifier.height(18.dp))
                        }

                        // Main Toggle Button
                        Button(
                            onClick = {
                                if (isRecording) {
                                    MeetingRecordingService.stop(context)
                                } else {
                                    if (hasMicPermission) {
                                        MeetingRecordingService.start(context)
                                    } else {
                                        micLauncher.launch(Manifest.permission.RECORD_AUDIO)
                                    }
                                }
                            },
                            colors = ButtonDefaults.buttonColors(
                                containerColor = if (isRecording) DesignTokens.Colors.StatusRecording else DesignTokens.Colors.PrimaryBlue
                            ),
                            shape = RoundedCornerShape(14.dp),
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(50.dp)
                        ) {
                            Icon(
                                imageVector = if (isRecording) Icons.Default.Stop else Icons.Default.Mic,
                                contentDescription = null,
                                modifier = Modifier.size(20.dp)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = if (isRecording) "Stop Meeting Recording" else "Start Meeting Recording",
                                fontSize = 15.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }
                    }
                }
            }

            // Quick Action Buttons (Save to PC / Copy Markdown)
            item {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    Button(
                        onClick = { sendNotesToPc() },
                        enabled = !isSendingToPc && (executiveSummary.isNotBlank() || liveTranscript.isNotBlank()),
                        colors = ButtonDefaults.buttonColors(
                            containerColor = DesignTokens.CardBgElevated
                        ),
                        border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.ElectricBlue.copy(alpha = 0.5f)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .weight(1f)
                            .height(46.dp)
                    ) {
                        if (isSendingToPc) {
                            CircularProgressIndicator(
                                modifier = Modifier.size(16.dp),
                                strokeWidth = 2.dp,
                                color = DesignTokens.ElectricBlue
                            )
                        } else {
                            Icon(
                                imageVector = Icons.Default.Laptop,
                                contentDescription = null,
                                tint = DesignTokens.ElectricBlue,
                                modifier = Modifier.size(18.dp)
                            )
                        }
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(
                            text = "Save to PC",
                            color = DesignTokens.ElectricBlue,
                            fontSize = 13.sp,
                            fontWeight = FontWeight.SemiBold
                        )
                    }

                    Button(
                        onClick = { copyMarkdownToClipboard() },
                        enabled = executiveSummary.isNotBlank() || liveTranscript.isNotBlank(),
                        colors = ButtonDefaults.buttonColors(
                            containerColor = DesignTokens.CardBgElevated
                        ),
                        border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.Colors.BorderSubtle),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .weight(1f)
                            .height(46.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.ContentCopy,
                            contentDescription = null,
                            tint = DesignTokens.Colors.TextPrimary,
                            modifier = Modifier.size(18.dp)
                        )
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(
                            text = "Copy Notes",
                            color = DesignTokens.Colors.TextPrimary,
                            fontSize = 13.sp,
                            fontWeight = FontWeight.SemiBold
                        )
                    }
                }
            }

            // Executive Summary Card
            item {
                Surface(
                    shape = RoundedCornerShape(16.dp),
                    color = DesignTokens.Colors.CardSurface,
                    border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.Colors.BorderSubtle),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = Icons.Default.AutoAwesome,
                                    contentDescription = null,
                                    tint = DesignTokens.PurpleAccent,
                                    modifier = Modifier.size(18.dp)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "Executive Summary",
                                    fontSize = 15.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = DesignTokens.Colors.TextPrimary
                                )
                            }
                            if (executiveSummary.isNotBlank()) {
                                Text(
                                    text = "AI Generated",
                                    fontSize = 11.sp,
                                    color = DesignTokens.PurpleAccent,
                                    fontWeight = FontWeight.Medium
                                )
                            }
                        }

                        Spacer(modifier = Modifier.height(10.dp))

                        if (executiveSummary.isNotBlank()) {
                            Text(
                                text = executiveSummary,
                                fontSize = 14.sp,
                                lineHeight = 21.sp,
                                color = DesignTokens.Colors.TextSecondary
                            )
                        } else {
                            Text(
                                text = "As your conversation progresses, Gemini will automatically summarize core themes, context, and executive takeaways.",
                                fontSize = 13.sp,
                                lineHeight = 19.sp,
                                color = DesignTokens.Colors.TextSubtle
                            )
                        }
                    }
                }
            }

            // Key Decisions Section
            item {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Icon(
                        imageVector = Icons.Default.Gavel,
                        contentDescription = null,
                        tint = DesignTokens.AmberAccent,
                        modifier = Modifier.size(18.dp)
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "Key Decisions (${decisions.size})",
                        fontSize = 15.sp,
                        fontWeight = FontWeight.Bold,
                        color = DesignTokens.Colors.TextPrimary
                    )
                }
            }

            if (decisions.isEmpty()) {
                item {
                    Surface(
                        shape = RoundedCornerShape(12.dp),
                        color = DesignTokens.Colors.CardSurface,
                        border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.Colors.BorderSubtle),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Box(
                            modifier = Modifier.padding(16.dp),
                            contentAlignment = Alignment.CenterStart
                        ) {
                            Text(
                                text = "Agreed decisions and team alignments will appear here as they are discussed.",
                                fontSize = 13.sp,
                                color = DesignTokens.Colors.TextSubtle
                            )
                        }
                    }
                }
            } else {
                items(decisions) { decision ->
                    Surface(
                        shape = RoundedCornerShape(12.dp),
                        color = DesignTokens.Colors.CardSurface,
                        border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.AmberAccent.copy(alpha = 0.3f)),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier.padding(14.dp),
                            verticalAlignment = Alignment.Top
                        ) {
                            Box(
                                modifier = Modifier
                                    .padding(top = 2.dp)
                                    .size(8.dp)
                                    .background(DesignTokens.AmberAccent, CircleShape)
                            )
                            Spacer(modifier = Modifier.width(10.dp))
                            Text(
                                text = decision,
                                fontSize = 13.sp,
                                lineHeight = 19.sp,
                                color = DesignTokens.Colors.TextPrimary
                            )
                        }
                    }
                }
            }

            // Action Items Section
            item {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Icon(
                        imageVector = Icons.Default.CheckCircle,
                        contentDescription = null,
                        tint = DesignTokens.StatusGreen,
                        modifier = Modifier.size(18.dp)
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "Action Items (${actionItems.size})",
                        fontSize = 15.sp,
                        fontWeight = FontWeight.Bold,
                        color = DesignTokens.Colors.TextPrimary
                    )
                }
            }

            if (actionItems.isEmpty()) {
                item {
                    Surface(
                        shape = RoundedCornerShape(12.dp),
                        color = DesignTokens.Colors.CardSurface,
                        border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.Colors.BorderSubtle),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Box(
                            modifier = Modifier.padding(16.dp),
                            contentAlignment = Alignment.CenterStart
                        ) {
                            Text(
                                text = "Assigned tasks, deadlines, and deliverables will be captured dynamically.",
                                fontSize = 13.sp,
                                color = DesignTokens.Colors.TextSubtle
                            )
                        }
                    }
                }
            } else {
                items(actionItems) { item ->
                    var isChecked by remember { mutableStateOf(false) }
                    Surface(
                        shape = RoundedCornerShape(12.dp),
                        color = DesignTokens.Colors.CardSurface,
                        border = androidx.compose.foundation.BorderStroke(
                            1.dp,
                            if (isChecked) DesignTokens.StatusGreen.copy(alpha = 0.3f) else DesignTokens.Colors.BorderSubtle
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable { isChecked = !isChecked }
                    ) {
                        Row(
                            modifier = Modifier.padding(12.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Checkbox(
                                checked = isChecked,
                                onCheckedChange = { isChecked = it },
                                colors = CheckboxDefaults.colors(
                                    checkedColor = DesignTokens.StatusGreen,
                                    uncheckedColor = DesignTokens.Colors.TextMuted
                                )
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = item,
                                fontSize = 13.sp,
                                lineHeight = 19.sp,
                                color = if (isChecked) DesignTokens.Colors.TextSubtle else DesignTokens.Colors.TextPrimary
                            )
                        }
                    }
                }
            }

            // Rolling Transcript (Collapsible)
            item {
                Surface(
                    shape = RoundedCornerShape(16.dp),
                    color = DesignTokens.Colors.CardSurface,
                    border = androidx.compose.foundation.BorderStroke(1.dp, DesignTokens.Colors.BorderSubtle),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween,
                            modifier = Modifier
                                .fillMaxWidth()
                                .clickable { isTranscriptExpanded = !isTranscriptExpanded }
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = Icons.Default.Description,
                                    contentDescription = null,
                                    tint = DesignTokens.Colors.PrimaryLightBlue,
                                    modifier = Modifier.size(18.dp)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "Live Rolling Transcript",
                                    fontSize = 15.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = DesignTokens.Colors.TextPrimary
                                )
                            }
                            Icon(
                                imageVector = if (isTranscriptExpanded) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                                contentDescription = null,
                                tint = DesignTokens.Colors.TextMuted
                            )
                        }

                        if (isTranscriptExpanded) {
                            Spacer(modifier = Modifier.height(10.dp))
                            if (liveTranscript.isNotBlank()) {
                                Text(
                                    text = liveTranscript,
                                    fontSize = 13.sp,
                                    lineHeight = 19.sp,
                                    color = DesignTokens.Colors.TextSecondary
                                )
                            } else {
                                Text(
                                    text = "Transcript segments will stream in real-time as the meeting is recorded.",
                                    fontSize = 12.sp,
                                    color = DesignTokens.Colors.TextSubtle
                                )
                            }
                        }
                    }
                }
                Spacer(modifier = Modifier.height(30.dp))
            }
        }
    }

    if (showClearDialog) {
        AlertDialog(
            onDismissRequest = { showClearDialog = false },
            title = {
                Text(
                    text = "Clear Meeting Session?",
                    color = DesignTokens.Colors.TextPrimary,
                    fontWeight = FontWeight.Bold
                )
            },
            text = {
                Text(
                    text = "This will reset current meeting minutes, action items, and live transcript.",
                    color = DesignTokens.Colors.TextMuted,
                    fontSize = 14.sp
                )
            },
            confirmButton = {
                TextButton(
                    onClick = {
                        MeetingRecordingService.clearSession()
                        showClearDialog = false
                    }
                ) {
                    Text("Clear", color = DesignTokens.Colors.StatusRecording, fontWeight = FontWeight.Bold)
                }
            },
            dismissButton = {
                TextButton(onClick = { showClearDialog = false }) {
                    Text("Cancel", color = DesignTokens.Colors.TextMuted)
                }
            },
            containerColor = DesignTokens.CardBgElevated
        )
    }
}
